# Generated by Django 4.1.2 on 2022-11-10 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Username')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Last Name')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gender')),
                ('user_category', models.CharField(choices=[('User', 'User'), ('Mod', 'Moderator')], default='User', max_length=200, verbose_name='User Category')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, verbose_name='Verification Code')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True, help_text='The timestamp of the moment of expiry of the saved token.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
