# Generated by Django 4.1.2 on 2022-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp of creation of otp.'),
        ),
    ]
