# Generated by Django 4.1.3 on 2022-12-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_backend_api', '0004_alter_myuser_email_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pics/'),
        ),
    ]
